package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "ACTIVITY")
public class Activity implements java.io.Serializable {

	private ActivityId id;

	public Activity() {
	}

	public Activity(ActivityId id) {
		this.id = id;
	}

	@AttributeOverrides({
			@AttributeOverride(name = "activityId", column = @Column(name = "ACTIVITY_ID", nullable = false, length = 45)),
			@AttributeOverride(name = "activityInfoActivityInfoId", column = @Column(name = "ACTIVITY_INFO_ACTIVITY_INFO_ID", nullable = false)) })
	public ActivityId getId() {
		return this.id;
	}

	public void setId(ActivityId id) {
		this.id = id;
	}

}
