package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Version;

/**
 * ActivityId generated by hbm2java
 */
@Entity
@Embeddable
public class ActivityId implements java.io.Serializable {

	@Id
	@GeneratedValue
	private String activityId;
	private int activityInfoActivityInfoId;

	public ActivityId() {
	}

	public ActivityId(String activityId, int activityInfoActivityInfoId) {
		this.activityId = activityId;
		this.activityInfoActivityInfoId = activityInfoActivityInfoId;
	}

	@Column(name = "ACTIVITY_ID", nullable = false, length = 45)
	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	@Column(name = "ACTIVITY_INFO_ACTIVITY_INFO_ID", nullable = false)
	public int getActivityInfoActivityInfoId() {
		return this.activityInfoActivityInfoId;
	}

	public void setActivityInfoActivityInfoId(int activityInfoActivityInfoId) {
		this.activityInfoActivityInfoId = activityInfoActivityInfoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivityId))
			return false;
		ActivityId castOther = (ActivityId) other;

		return ((this.getActivityId() == castOther.getActivityId()) || (this
				.getActivityId() != null && castOther.getActivityId() != null && this
				.getActivityId().equals(castOther.getActivityId())))
				&& (this.getActivityInfoActivityInfoId() == castOther
						.getActivityInfoActivityInfoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getActivityId() == null ? 0 : this.getActivityId()
						.hashCode());
		result = 37 * result + this.getActivityInfoActivityInfoId();
		return result;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}
