package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ActivityInfo generated by hbm2java
 */
@Entity
@Table(name = "ACTIVITY_INFO")
public class ActivityInfo implements java.io.Serializable {

	private Integer activityInfoId;
	private String name;
	private String description;

	public ActivityInfo() {
	}

	public ActivityInfo(String name, String description) {
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACTIVITY_INFO_ID", unique = true, nullable = false)
	public Integer getActivityInfoId() {
		return this.activityInfoId;
	}

	public void setActivityInfoId(Integer activityInfoId) {
		this.activityInfoId = activityInfoId;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}
