package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.AssociationOverrides;
import javax.persistence.AssociationOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * CoachInfo generated by hbm2java
 */
@Entity
@Table(name = "COACH_INFO_TRAINEE_INFO")
public class CoachTraineeAssociation implements java.io.Serializable {

	@GeneratedValue
	@Id
	@Column(name = "COACH_INFO_TRAINEE_INFO_ID", unique = true, nullable = false)
	private int coachInfoTraineeInfoId;
	

	@Column(name="ACTIVE")
	private boolean active;
	
	@ManyToOne
	@JoinColumn(name="COACH_INFO_ID")
	private CoachInfo coachInfo;
	
	@ManyToOne
	@JoinColumn(name="TRAINEE_INFO_ID")
	private TraineeInfo traineeInfo;
	
	public int getCoachInfoTraineeInfoId() {
		return coachInfoTraineeInfoId;
	}
	
	public TraineeInfo getTraineeInfo() {
		return traineeInfo;
	}

	public void setTraineeInfo(TraineeInfo traineeInfo) {
		this.traineeInfo = traineeInfo;
	}

	public CoachInfo getCoachInfo() {
		return coachInfo;
	}

	public void setCoachInfo(CoachInfo coachInfo) {
		this.coachInfo = coachInfo;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public CoachTraineeAssociation() {
	}

	public CoachTraineeAssociation(int coachInfoTraineeInfoId) {
		this.coachInfoTraineeInfoId = coachInfoTraineeInfoId;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}




}
