package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * FileCabinet generated by hbm2java
 */
@Entity
@Table(name = "FILE_CABINET")
public class FileCabinet implements java.io.Serializable {

	private Integer fileCabinetId;
	private String fileName;
	private byte[] fileBlob;
	private String description;

	public FileCabinet() {
	}

	public FileCabinet(String fileName, byte[] fileBlob) {
		this.fileName = fileName;
		this.fileBlob = fileBlob;
	}

	public FileCabinet(String fileName, byte[] fileBlob, String description) {
		this.fileName = fileName;
		this.fileBlob = fileBlob;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FILE_CABINET_ID", unique = true, nullable = false)
	public Integer getFileCabinetId() {
		return this.fileCabinetId;
	}

	public void setFileCabinetId(Integer fileCabinetId) {
		this.fileCabinetId = fileCabinetId;
	}

	@Column(name = "FILE_NAME", nullable = false, length = 45)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_BLOB", nullable = false)
	public byte[] getFileBlob() {
		return this.fileBlob;
	}

	public void setFileBlob(byte[] fileBlob) {
		this.fileBlob = fileBlob;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}
