package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * PlanInfo generated by hbm2java
 */
@Entity
@Table(name = "PLAN_INFO")
public class PlanInfo implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PLAN_INFO_ID", unique = true, nullable = false)
	private Integer planInfoId;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy="planInfo",cascade=CascadeType.ALL, orphanRemoval=false)
	private Set <Plan> plans = new HashSet<Plan>();
	
	@Column(name = "NAME", length = 45)
	private String name;
	
	@Column(name = "DESCRIPTION", length = 100)
	private String description;
	
	@OneToOne(cascade= CascadeType.ALL)
	@JoinColumn(name="FILE_RECORD_ID")
	private FileRecord fileRecord;

	@ManyToOne
	@JoinColumn(name="COACH_INFO_ID") 
	private CoachInfo coachInfo;
	
	@Column(name="ACTIVE", nullable= false)
	private boolean active;

	public FileRecord getFileRecord() {
		return fileRecord;
	}

	public void setFileRecord(FileRecord fileRecord) {
		this.fileRecord = fileRecord;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public PlanInfo() {
	}


	public PlanInfo( String name, String description) {

		this.name = name;
		this.description = description;
	}


	public Integer getPlanInfoId() {
		return this.planInfoId;
	}

	public void setPlanInfoId(Integer planInfoId) {
		this.planInfoId = planInfoId;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public CoachInfo getCoachInfo() {
		return coachInfo;
	}

	public void setCoachInfo(CoachInfo coachInfo) {
		this.coachInfo = coachInfo;
	}
	
	public Set<Plan> getPlans() {
		return plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}
	
	public boolean equals (Object object) {
		if(object instanceof PlanInfo) {
			PlanInfo planInfo = (PlanInfo) object; 
			if(this.planInfoId.equals(planInfo.planInfoId)) {
				return true;
				
			}
		}

		return false;
	}
	
	public int hashCode(){
		if(planInfoId!=null) {
			return planInfoId.hashCode();
		}
		else {
			return super.hashCode();
		}
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


}
