package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "ROLES")
public class Roles implements java.io.Serializable {

	@GeneratedValue
	@Id
	@Column(name = "ROLES_ID", unique = true, nullable = false, length = 45)
	private String rolesId;

	@Column(name = "ROLE_DESCRIPTION_ID", nullable = false)
	private int roleDescriptionId;
	
	@OneToOne
	@JoinColumn(name="LOGIN_ID") 
	private Login login;
	
	@OneToOne
	@JoinColumn(name="COACH_INFO_ID") 
	private CoachInfo coachInfo;
	
	@OneToOne
	@JoinColumn(name="TRAINEE_INFO_ID") 
	private CoachInfo traineeInfo;



	public CoachInfo getCoachInfo() {
		return coachInfo;
	}

	public void setCoachInfo(CoachInfo coachInfo) {
		this.coachInfo = coachInfo;
	}
	public CoachInfo getTraineeInfo() {
		return traineeInfo;
	}

	public void setTraineeInfo(CoachInfo traineeInfo) {
		this.traineeInfo = traineeInfo;
	}

	public Login getLogin() {
		return login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	public Roles() {
	}

	public Roles(String rolesId,  int roleDescriptionId) {
		this.rolesId = rolesId;

		this.roleDescriptionId = roleDescriptionId;
	}




	public String getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(String rolesId) {
		this.rolesId = rolesId;
	}

	public int getRoleDescriptionId() {
		return this.roleDescriptionId;
	}

	public void setRoleDescriptionId(int roleDescriptionId) {
		this.roleDescriptionId = roleDescriptionId;
	}

	@Version
	protected Integer version;



	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


}
