package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RoleDescription generated by hbm2java
 */
@Entity
@Table(name = "ROLE_DESCRIPTION")
public class RoleDescription implements java.io.Serializable {

	private Integer roleDescriptionId;
	private String name;

	public RoleDescription() {
	}

	public RoleDescription(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROLE_DESCRIPTION_ID", unique = true, nullable = false)
	public Integer getRoleDescriptionId() {
		return this.roleDescriptionId;
	}

	public void setRoleDescriptionId(Integer roleDescriptionId) {
		this.roleDescriptionId = roleDescriptionId;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}
