package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Version;

/**
 * ScheduleUnitId generated by hbm2java
 */
@Entity
@Embeddable
public class ScheduleUnitId implements java.io.Serializable {

	@Id
	@GeneratedValue
	private int idScheduleUnit;
	private String activityActivityId;

	public ScheduleUnitId() {
	}

	public ScheduleUnitId(int idScheduleUnit, String activityActivityId) {
		this.idScheduleUnit = idScheduleUnit;
		this.activityActivityId = activityActivityId;
	}

	@Column(name = "idSCHEDULE_UNIT", nullable = false)
	public int getIdScheduleUnit() {
		return this.idScheduleUnit;
	}

	public void setIdScheduleUnit(int idScheduleUnit) {
		this.idScheduleUnit = idScheduleUnit;
	}

	@Column(name = "ACTIVITY_ACTIVITY_ID", nullable = false, length = 45)
	public String getActivityActivityId() {
		return this.activityActivityId;
	}

	public void setActivityActivityId(String activityActivityId) {
		this.activityActivityId = activityActivityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScheduleUnitId))
			return false;
		ScheduleUnitId castOther = (ScheduleUnitId) other;

		return (this.getIdScheduleUnit() == castOther.getIdScheduleUnit())
				&& ((this.getActivityActivityId() == castOther
						.getActivityActivityId()) || (this
						.getActivityActivityId() != null
						&& castOther.getActivityActivityId() != null && this
						.getActivityActivityId().equals(
								castOther.getActivityActivityId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdScheduleUnit();
		result = 37
				* result
				+ (getActivityActivityId() == null ? 0 : this
						.getActivityActivityId().hashCode());
		return result;
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

}
