package com.healthElite.model;

// Generated Dec 23, 2012 2:49:44 PM by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TraineeInfo generated by hbm2java
 */
@Entity
@Table(name = "TRAINEE_INFO")
public class TraineeInfo implements java.io.Serializable {

	@GeneratedValue
	@Id
	@Column(name = "TRAINEE_INFO_ID", unique = true, nullable = false)
	private int traineeInfoId;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy="traineeInfo")
	private Set <CoachTraineeAssociation> coachTraineeAssociations;
	
	@OneToMany(fetch = FetchType.EAGER,mappedBy="traineeInfo",cascade=CascadeType.ALL, orphanRemoval=false) 
	private Set <Plan> plans;


	@OneToOne(mappedBy="traineeInfo")
	private Roles roles;
	
	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public TraineeInfo() {
	}

	public TraineeInfo(int traineeInfoId) {
		this.traineeInfoId = traineeInfoId;
	}


	public int getTraineeInfoId() {
		return this.traineeInfoId;
	}

	public void setTraineeInfoId(int traineeInfoId) {
		this.traineeInfoId = traineeInfoId;
	}
	

	public Set<Plan> getPlans() {
		return plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}
	
	public void addPlan(Plan plan) {
		plans.add(plan);
	}

	@Version
	protected Integer version;

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	


}
